export const WORK: Record<string, string[]> = {
  "Servicefartøy mannskap": ["Skipper/Styrmann", "Matros", "Kokekyndig", "Annet"],
  Havbruk: ["Operativt", "Akvatekniker m/fagbrev", "Laseroperatør", "Fôringsoperatør", "Annet"],
  Fiskeri: ["Skipper/Styrmann", "Matros", "Annet"],
  "Logistikk og støtte": ["Supply", "Offshore service", "Annet"],
  Annet: ["Annet"],
};

export const STCW_MODULES = [
  "Sjøoverlevelse (PST)",
  "Brannvern (FPFF)",
  "Førstehjelp (EFA)",
  "PSSR",
];

export const HERO_POINTS = [
  {
    icon: "🧑‍✈️",
    text: "Erfarne skipsførere og mannskap følger opp oppdraget sammen med deg.",
  },
  {
    icon: "🌊",
    text: "Bemanning for havbruk, fiskeri og spesialfartøy levert når operasjonen krever det.",
  },
  {
    icon: "🛡️",
    text: "GDPR-trygg prosess med kontrollert dokumentasjon og dedikert støtte.",
  },
];

export const BENEFITS = [
  {
    icon: "🧭",
    title: "Erfaring fra sjøen",
    text: "Vi har selv stått på broa og dekk – og vet hvilket mannskap som leverer innen alle maritime disipliner.",
  },
  {
    icon: "🪝",
    title: "Rask mobilisering",
    text: "Eget nettverk av sertifiserte sjøfolk gjør at vi kan mobilisere på kort varsel over hele kysten og offshore.",
  },
  {
    icon: "🛡️",
    title: "Kvalitet og trygghet",
    text: "Strukturerte prosesser, HMS-fokus og tett oppfølging gir forutsigbare leveranser.",
  },
  {
    icon: "🤝",
    title: "Langsiktige partnerskap",
    text: "Vi lærer kunden å kjenne, bygger team rundt fartøyet og følger opp gjennom hele oppdraget.",
  },
];

export const PROCESS_STEPS = [
  {
    title: "Behovsavklaring",
    text: "Samtale om fartøy, oppdrag og kompetansekrav – inklusive sertifikater og turnus.",
  },
  {
    title: "Screening & verifisering",
    text: "Vi intervjuer, referansesjekker og kontrollerer dokumentasjon før kandidatene godkjennes.",
  },
  {
    title: "Presentasjon & oppstart",
    text: "Du får klare forslag med tilgjengelighet og løsningsforslag. Vi koordinerer oppstarten.",
  },
  {
    title: "Oppfølging om bord",
    text: "Teamet vårt holder dialogen med skipper og mannskap og sikrer at alt fungerer som avtalt.",
  },
];

export const FAQS = [
  {
    q: "Hvordan registrerer jeg meg som jobbsøker?",
    a: "Bruk skjemaet under «Jobbsøker» og last opp CVen din. Vi kontakter deg når vi har et oppdrag som matcher erfaringen din.",
  },
  {
    q: "Hvor raskt kan dere levere personell?",
    a: "Behov som meldes inn på dagtid får normalt svar innen 24 timer. Ved akutte tilfeller følger vi opp etter avtale og prioriterer oppstart så raskt som mulig.",
  },
  {
    q: "Hvilke typer kontrakter tilbyr dere?",
    a: "Vi håndterer korttidsoppdrag, sesongbemanning og langsiktige engasjement. Vi tilpasser oss kundens struktur.",
  },
  {
    q: "Hvordan ivaretas personvern?",
    a: "Alle søknader lagres sikkert og deles ikke med tredjepart uten samtykke. Vi følger GDPR og interne retningslinjer for datasikkerhet.",
  },
];

export const COUNTIES = [
  "Agder",
  "Innlandet",
  "Møre og Romsdal",
  "Nordland",
  "Oslo",
  "Rogaland",
  "Troms og Finnmark",
  "Trøndelag",
  "Vestfold og Telemark",
  "Vestland",
  "Viken",
];

export const MUNICIPALITIES_BY_COUNTY: Record<string, string[]> = {
  Agder: [
    "Arendal",
    "Birkenes",
    "Bygland",
    "Bykle",
    "Evje og Hornnes",
    "Farsund",
    "Flekkefjord",
    "Froland",
    "Gjerstad",
    "Grimstad",
    "Hægebostad",
    "Iveland",
    "Kristiansand",
    "Kvinesdal",
    "Lillesand",
    "Lindesnes",
    "Lyngdal",
    "Risør",
    "Sirdal",
    "Tvedestrand",
    "Valle",
    "Vegårshei",
    "Åmli",
    "Åseral",
  ],
  Innlandet: [
    "Alvdal",
    "Dovre",
    "Eidskog",
    "Elverum",
    "Engerdal",
    "Etnedal",
    "Folldal",
    "Gausdal",
    "Gjøvik",
    "Gran",
    "Grue",
    "Hamar",
    "Kongsvinger",
    "Lesja",
    "Lillehammer",
    "Lom",
    "Løten",
    "Nord-Aurdal",
    "Nord-Fron",
    "Nord-Odal",
    "Os (Innlandet)",
    "Rendalen",
    "Ringebu",
    "Ringsaker",
    "Sel",
    "Skjåk",
    "Stange",
    "Stor-Elvdal",
    "Søndre Land",
    "Sør-Aurdal",
    "Sør-Fron",
    "Sør-Odal",
    "Tolga",
    "Trysil",
    "Tynset",
    "Vang",
    "Vestre Slidre",
    "Vestre Toten",
    "Vågå",
    "Våler (Innlandet)",
    "Østre Toten",
    "Øyer",
    "Øystre Slidre",
    "Åmot",
    "Åsnes",
  ],
  "Møre og Romsdal": [
    "Aukra",
    "Aure",
    "Averøy",
    "Fjord",
    "Giske",
    "Gjemnes",
    "Hareid",
    "Herøy (Møre og Romsdal)",
    "Hustadvika",
    "Kristiansund",
    "Molde",
    "Rauma",
    "Sande",
    "Smøla",
    "Stranda",
    "Sula",
    "Sunndal",
    "Surnadal",
    "Sykkylven",
    "Tingvoll",
    "Ulstein",
    "Vanylven",
    "Vestnes",
    "Volda",
    "Ålesund",
    "Ørsta",
  ],
  Nordland: [
    "Alstahaug",
    "Andøy",
    "Beiarn",
    "Bindal",
    "Bodø",
    "Brønnøy",
    "Bø",
    "Dønna",
    "Evenes",
    "Fauske",
    "Flakstad",
    "Gildeskål",
    "Grane",
    "Hadsel",
    "Hamarøy",
    "Hattfjelldal",
    "Hemnes",
    "Herøy (Nordland)",
    "Leirfjord",
    "Lødingen",
    "Lurøy",
    "Meløy",
    "Moskenes",
    "Narvik",
    "Nesna",
    "Rana",
    "Rødøy",
    "Røst",
    "Saltdal",
    "Sortland",
    "Steigen",
    "Sømna",
    "Sørfold",
    "Træna",
    "Vefsn",
    "Vega",
    "Vestvågøy",
    "Vevelstad",
    "Vågan",
    "Værøy",
    "Øksnes",
  ],
  Oslo: ["Oslo"],
  Rogaland: [
    "Bjerkreim",
    "Bokn",
    "Eigersund",
    "Gjesdal",
    "Haugesund",
    "Hjelmeland",
    "Hå",
    "Karmøy",
    "Klepp",
    "Kvitsøy",
    "Lund",
    "Randaberg",
    "Sandnes",
    "Sauda",
    "Sokndal",
    "Sola",
    "Stavanger",
    "Strand",
    "Suldal",
    "Time",
    "Tysvær",
    "Utsira",
    "Vindafjord",
  ],
  "Troms og Finnmark": [
    "Alta",
    "Balsfjord",
    "Bardu",
    "Berlevåg",
    "Båtsfjord",
    "Dyrøy",
    "Gamvik",
    "Gratangen",
    "Hammerfest",
    "Harstad",
    "Hasvik",
    "Ibestad",
    "Karasjok",
    "Kautokeino",
    "Kvæfjord",
    "Kvænangen",
    "Kåfjord",
    "Lebesby",
    "Loppa",
    "Lyngen",
    "Målselv",
    "Måsøy",
    "Nesseby",
    "Nordkapp",
    "Nordreisa",
    "Porsanger",
    "Salangen",
    "Senja",
    "Skjervøy",
    "Tjeldsund",
    "Sør-Varanger",
    "Storfjord",
    "Tana",
    "Tromsø",
    "Vadsø",
    "Vardø",
  ],
  Trøndelag: [
    "Flatanger",
    "Frosta",
    "Frøya",
    "Grong",
    "Høylandet",
    "Heim",
    "Hitra",
    "Holtålen",
    "Inderøy",
    "Indre Fosen",
    "Leka",
    "Levanger",
    "Lierne",
    "Malvik",
    "Melhus",
    "Meråker",
    "Midtre Gauldal",
    "Namsos",
    "Namsskogan",
    "Nærøysund",
    "Oppdal",
    "Orkland",
    "Osen",
    "Overhalla",
    "Rennebu",
    "Rindal",
    "Røros",
    "Røyrvik",
    "Selbu",
    "Skaun",
    "Snåsa",
    "Steinkjer",
    "Stjørdal",
    "Trondheim",
    "Tydal",
    "Verdal",
    "Ørland",
    "Åfjord",
  ],
  "Vestfold og Telemark": [
    "Bamble",
    "Drangedal",
    "Fyresdal",
    "Færder",
    "Hjartdal",
    "Holmestrand",
    "Horten",
    "Kragerø",
    "Kviteseid",
    "Larvik",
    "Midt-Telemark",
    "Nissedal",
    "Nome",
    "Notodden",
    "Porsgrunn",
    "Sandefjord",
    "Seljord",
    "Siljan",
    "Skien",
    "Tinn",
    "Tokke",
    "Tønsberg",
    "Vinje",
  ],
  Vestland: [
    "Alver",
    "Askøy",
    "Austevoll",
    "Austrheim",
    "Aurland",
    "Bergen",
    "Bremanger",
    "Bjørnafjorden",
    "Bømlo",
    "Eidfjord",
    "Etne",
    "Fedje",
    "Fitjar",
    "Gloppen",
    "Gulen",
    "Kvinnherad",
    "Høyanger",
    "Hyllestad",
    "Kinn",
    "Kvam",
    "Luster",
    "Lærdal",
    "Masfjorden",
    "Modalen",
    "Osterøy",
    "Samnanger",
    "Sogndal",
    "Solund",
    "Stad",
    "Stord",
    "Stryn",
    "Sunnfjord",
    "Sveio",
    "Tysnes",
    "Ullensvang",
    "Ulvik",
    "Vaksdal",
    "Vik",
    "Voss",
    "Øygarden",
    "Årdal",
  ],
  Viken: [
    "Aremark",
    "Asker",
    "Aurskog-Høland",
    "Bærum",
    "Drammen",
    "Eidsvoll",
    "Enebakk",
    "Flå",
    "Flesberg",
    "Fredrikstad",
    "Frogn",
    "Gjerdrum",
    "Gol",
    "Halden",
    "Hvaler",
    "Hemsedal",
    "Hol",
    "Hole",
    "Hurdal",
    "Indre Østfold",
    "Jevnaker",
    "Kongsberg",
    "Krødsherad",
    "Lier",
    "Lillestrøm",
    "Lunner",
    "Marker",
    "Modum",
    "Moss",
    "Nannestad",
    "Nes",
    "Nesbyen",
    "Nesodden",
    "Nittedal",
    "Nordre Follo",
    "Nore og Uvdal",
    "Rakkestad",
    "Ringerike",
    "Rollag",
    "Råde",
    "Sarpsborg",
    "Sigdal",
    "Skiptvet",
    "Ullensaker",
    "Vestby",
    "Våler (Viken)",
    "Øvre Eiker",
    "Ål",
    "Ås",
  ],
};

export const CONTACT_POINTS = [
  { label: "Ring oss", value: "923 28 850", href: "tel:92328850" },
  { label: "Send e-post", value: "isak@bluecrew.no", href: "mailto:isak@bluecrew.no" },
  { label: "Besøk oss", value: "Østenbekkveien 43, 9403 Harstad" },
];

export const SOCIAL_LINKS = [
  {
    label: "LinkedIn",
    href: "https://www.linkedin.com/company/bluecrew-as/",
    description: "Følg oss for innsikt fra prosjektene våre",
  },
];
