import type { CSSProperties } from "react";

export const sx: Record<string, CSSProperties> = {
  page: {
    fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif",
    background: "#F8FAFC",
    color: "#0F172A",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  topbar: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    background: "#07162B",
    color: "#fff",
    borderBottom: "1px solid rgba(255,255,255,.12)",
    boxShadow: "0 8px 30px rgba(7,22,43,.18)",
  },
  wrap: {
    maxWidth: 1120,
    margin: "0 auto",
    padding: "12px 20px",
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  logoBox: { display: "grid" },
  logoText: { fontWeight: 900, letterSpacing: "-0.02em", fontSize: 20 },
  logoTag: { fontSize: 12, opacity: 0.85 },
  nav: { display: "flex", gap: 18, marginLeft: "auto" },
  navLink: {
    color: "rgba(255,255,255,.86)",
    textDecoration: "none",
    fontSize: 14,
    fontWeight: 600,
    padding: "8px 0",
  },
  navLinkActive: {
    color: "#38bdf8",
  },
  main: {
    flex: 1,
  },
  hero: {
    padding: "72px 0 48px",
    background: "linear-gradient(180deg, #07162B 0%, #0B1F3A 45%, #0E1E3C 100%)",
    color: "#E2E8F0",
    borderBottom: "1px solid rgba(255,255,255,0.12)",
  },
  heroWrap: { maxWidth: 960, margin: "0 auto", padding: "0 20px", textAlign: "center" },
  heroPill: {
    display: "inline-block",
    padding: "6px 12px",
    borderRadius: 999,
    background: "rgba(59,130,246,0.18)",
    color: "#bfdbfe",
    fontSize: 12,
    letterSpacing: ".08em",
    marginBottom: 12,
    textTransform: "uppercase",
  },
  h1: {
    fontSize: 44,
    fontWeight: 900,
    lineHeight: 1.1,
    margin: 0,
    color: "#E2E8F0",
    letterSpacing: "-0.02em",
  },
  h1Sub: {
    marginTop: 12,
    color: "#cbd5f5",
    fontSize: 19,
    maxWidth: 720,
    marginLeft: "auto",
    marginRight: "auto",
  },
  lead: { marginTop: 12, color: "#374151", fontSize: 18 },
  ctaRow: { display: "flex", gap: 12, marginTop: 24, justifyContent: "center", flexWrap: "wrap" },
  btnMain: {
    padding: "14px 22px",
    borderRadius: 12,
    border: "1px solid #1d4ed8",
    background: "linear-gradient(180deg, #1d4ed8, #1e40af)",
    color: "#fff",
    fontWeight: 800,
    textDecoration: "none",
    boxShadow: "0 8px 20px rgba(30,64,175,0.35)",
    transition: "all 0.2s ease",
    display: "inline-block",
  },
  btnGhost: {
    padding: "14px 22px",
    borderRadius: 12,
    border: "1px solid rgba(226,232,240,0.35)",
    background: "rgba(15,23,42,0.35)",
    color: "#E2E8F0",
    fontWeight: 700,
    textDecoration: "none",
    transition: "all 0.2s ease",
    display: "inline-block",
  },
  badges: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 10,
    listStyle: "none",
    padding: 0,
    margin: "32px auto 0",
    maxWidth: 900,
  },
  badge: {
    background: "rgba(15,23,42,0.45)",
    border: "1px solid rgba(226,232,240,0.22)",
    color: "#E2E8F0",
    borderRadius: 12,
    padding: "12px 14px",
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    gap: 8,
    justifyContent: "center",
    boxShadow: "0 8px 22px rgba(15,23,42,0.35)",
  },
  badgeIcon: { fontSize: 16 },
  section: { padding: "56px 0" },
  sectionAlt: { padding: "56px 0", background: "#fff" },
  wrapNarrow: { maxWidth: 900, margin: "0 auto", padding: "0 20px" },
  h2: { fontSize: 32, fontWeight: 900, margin: 0, color: "#0B1F3A", letterSpacing: "-0.01em" },
  leadSmall: { fontSize: 17, color: "#475569", marginTop: 12 },
  loading: {
    fontSize: 16,
    color: "#1e293b",
    padding: "32px 0",
    textAlign: "center",
  },
  cards3: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 24,
    alignItems: "stretch",
  },
  cardService: {
    background: "#fff",
    border: "1px solid #E2E8F0",
    borderRadius: 16,
    padding: 24,
    boxShadow: "0 6px 24px rgba(2,6,23,0.08)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    textAlign: "left",
    transition: "transform .2s ease, box-shadow .2s ease",
  },
  cardIcon: { fontSize: 32, marginBottom: 8 },
  cardTitle: {
    fontWeight: 800,
    fontSize: 20,
    color: "#0B1F3A",
    marginBottom: 8,
  },
  cardList: { margin: 0, paddingLeft: 18, lineHeight: 1.6, color: "#334155" },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 20,
  },
  featureCard: {
    background: "#fff",
    border: "1px solid #E2E8F0",
    borderRadius: 16,
    padding: 22,
    boxShadow: "0 6px 20px rgba(2,6,23,0.06)",
    display: "grid",
    gap: 10,
    textAlign: "left",
  },
  featureIcon: { fontSize: 28 },
  featureTitle: { fontSize: 18, fontWeight: 800, color: "#0B1F3A", margin: 0 },
  featureText: { margin: 0, fontSize: 15, color: "#334155", lineHeight: 1.6 },
  processGrid: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 18,
  },
  processStep: {
    background: "#fff",
    border: "1px solid #E2E8F0",
    borderRadius: 16,
    padding: 22,
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
    boxShadow: "0 8px 24px rgba(2,6,23,0.06)",
  },
  stepNumber: {
    width: 36,
    height: 36,
    borderRadius: "999px",
    background: "#0B1F3A",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 16,
  },
  stepBody: { display: "grid", gap: 6 },
  stepTitle: { margin: 0, fontSize: 17, fontWeight: 700, color: "#0B1F3A" },
  stepText: { margin: 0, fontSize: 15, color: "#334155", lineHeight: 1.6 },
  faqList: { display: "grid", gap: 12 },
  faqItem: {
    border: "1px solid #E2E8F0",
    borderRadius: 14,
    background: "#fff",
    padding: 0,
    overflow: "hidden",
    boxShadow: "0 4px 16px rgba(2,6,23,0.05)",
  },
  faqSummary: {
    padding: "16px 20px",
    listStyle: "none",
    cursor: "pointer",
    fontWeight: 700,
    color: "#0B1F3A",
    outline: "none",
  },
  faqContent: {
    margin: 0,
    padding: "0 20px 18px",
    fontSize: 15,
    color: "#334155",
    lineHeight: 1.6,
  },
  form: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 14,
    background: "#fff",
    border: "1px solid #E2E8F0",
    borderRadius: 16,
    padding: 20,
    marginTop: 16,
    boxShadow: "0 8px 24px rgba(2,6,23,0.08)",
  },
  label: { display: "grid", gap: 6, fontSize: 14, color: "#0F172A" },
  input: {
    padding: "11px 13px",
    borderRadius: 12,
    border: "1px solid #CBD5E1",
    background: "#fff",
    outline: "none",
  },
  inputErr: { borderColor: "#ef4444", boxShadow: "0 0 0 3px rgba(239,68,68,0.15)" },
  errText: { color: "#b91c1c", fontSize: 12 },
  ok: {
    background: "#ecfdf5",
    color: "#065f46",
    border: "1px solid #a7f3d0",
    padding: 12,
    borderRadius: 12,
    marginTop: 12,
  },
  tags: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 8 },
  tagItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 10px",
    border: "1px solid #CBD5E1",
    borderRadius: 999,
    background: "#F8FAFC",
    fontSize: 14,
  },
  inlineRadios: { display: "flex", gap: 16, marginTop: 8 },
  checkGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginTop: 10 },
  checkItem: { display: "flex", alignItems: "center", gap: 8 },
  contactGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 24,
    marginTop: 20,
  },
  contactTitle: {
    fontWeight: 800,
    color: "#0B1F3A",
    marginBottom: 8,
    fontSize: 17,
  },
  contactLine: { margin: "4px 0", fontSize: 15, color: "#334155" },
  contactLink: { color: "#0B1F3A", textDecoration: "none" },
  privacyBox: {
    marginTop: 28,
    background: "#F8FAFC",
    border: "1px solid #E2E8F0",
    borderRadius: 12,
    padding: 16,
    color: "#475569",
  },
  footer: {
    borderTop: "1px solid #E2E8F0",
    padding: "18px 0",
    background: "#fff",
    color: "#475569",
    fontSize: 14,
    marginTop: 40,
  },
};
