import type { CSSProperties } from "react";

export const sx: Record<string, CSSProperties> = {
  page: {
    fontFamily: "var(--font-geist-sans, 'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif)",
    background: "#f1f5f9",
    color: "#0f172a",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  topbar: {
    position: "sticky",
    top: 0,
    zIndex: 30,
    background: "rgba(7, 17, 36, 0.95)",
    color: "#fff",
    backdropFilter: "blur(10px)",
    borderBottom: "1px solid rgba(148, 197, 255, 0.18)",
    boxShadow: "0 18px 40px rgba(15, 23, 42, 0.28)",
  },
  wrap: {
    maxWidth: 1180,
    margin: "0 auto",
    padding: "14px 26px",
    display: "flex",
    alignItems: "center",
    gap: 20,
  },
  wrapNarrow: { maxWidth: 980, margin: "0 auto", padding: "0 26px" },
  logoBox: { display: "grid" },
  logoText: { fontWeight: 800, letterSpacing: "-0.03em", fontSize: 22 },
  logoTag: { fontSize: 12, opacity: 0.76, marginTop: -2 },
  nav: { display: "flex", gap: 22, marginLeft: "auto", alignItems: "center" },
  navLink: {
    color: "rgba(226, 232, 240, 0.82)",
    textDecoration: "none",
    fontSize: 15,
    fontWeight: 600,
    padding: "8px 0",
    transition: "color 0.2s ease",
  },
  navLinkActive: {
    color: "#38bdf8",
  },
  navLinkAccent: {
    color: "#0f172a",
    background: "#38bdf8",
    padding: "10px 16px",
    borderRadius: 999,
    fontWeight: 700,
    boxShadow: "0 10px 24px rgba(56, 189, 248, 0.35)",
  },
  main: {
    flex: 1,
  },
  hero: {
    padding: "92px 0 74px",
    background:
      "radial-gradient(circle at 20% -10%, rgba(56, 189, 248, 0.45), transparent 55%), radial-gradient(circle at 80% 0%, rgba(14, 165, 233, 0.35), transparent 58%), linear-gradient(180deg, #051426 0%, #0b1d3b 48%, #0f284d 100%)",
    color: "#e2e8f0",
    position: "relative",
    overflow: "hidden",
  },
  heroWrap: { maxWidth: 1180, margin: "0 auto", padding: "0 26px" },
  heroGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 48,
    alignItems: "center",
  },
  heroContent: { display: "grid", gap: 16 },
  heroPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 18px",
    borderRadius: 999,
    background: "rgba(56, 189, 248, 0.14)",
    color: "#bae6fd",
    fontSize: 12,
    letterSpacing: ".12em",
    textTransform: "uppercase",
    fontWeight: 700,
  },
  h1: {
    fontSize: 48,
    fontWeight: 900,
    lineHeight: 1.05,
    margin: 0,
    color: "#f8fafc",
    letterSpacing: "-0.03em",
  },
  h1Sub: {
    marginTop: 4,
    color: "#cbd5f5",
    fontSize: 20,
    maxWidth: 560,
  },
  heroPoints: {
    display: "grid",
    gap: 12,
    margin: "8px 0 0",
    padding: 0,
    listStyle: "none",
  },
  heroPoint: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    fontSize: 15,
    color: "#dbeafe",
    lineHeight: 1.5,
  },
  heroPointIcon: { fontSize: 18, lineHeight: "1" },
  ctaRow: {
    display: "flex",
    gap: 14,
    marginTop: 20,
    flexWrap: "wrap",
  },
  btnMain: {
    padding: "14px 24px",
    borderRadius: 14,
    border: "1px solid rgba(148, 197, 255, 0.4)",
    background: "linear-gradient(180deg, #38bdf8 0%, #0ea5e9 100%)",
    color: "#0f172a",
    fontWeight: 800,
    textDecoration: "none",
    boxShadow: "0 18px 38px rgba(56, 189, 248, 0.35)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },
  btnGhost: {
    padding: "14px 24px",
    borderRadius: 14,
    border: "1px solid rgba(226, 232, 240, 0.4)",
    background: "rgba(15, 23, 42, 0.45)",
    color: "#e2e8f0",
    fontWeight: 700,
    textDecoration: "none",
    transition: "transform 0.2s ease, border 0.2s ease",
  },
  heroCard: {
    background: "rgba(7, 17, 36, 0.75)",
    border: "1px solid rgba(148, 197, 255, 0.25)",
    borderRadius: 24,
    padding: 28,
    boxShadow: "0 28px 70px rgba(8, 25, 48, 0.55)",
    display: "grid",
    gap: 18,
  },
  heroCardHeading: {
    fontSize: 18,
    fontWeight: 700,
    color: "#f8fafc",
    margin: 0,
  },
  heroHighlights: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "grid",
    gap: 12,
  },
  heroHighlight: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    background: "rgba(15, 23, 42, 0.55)",
    borderRadius: 16,
    padding: "14px 18px",
    border: "1px solid rgba(148, 197, 255, 0.18)",
  },
  heroHighlightIcon: { fontSize: 20, lineHeight: "1" },
  heroHighlightText: { color: "#dbeafe", fontSize: 15, lineHeight: 1.5 },
  badges: {
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
    listStyle: "none",
    padding: 0,
    margin: "8px 0 0",
  },
  badge: {
    background: "rgba(15, 23, 42, 0.45)",
    border: "1px solid rgba(148, 197, 255, 0.25)",
    color: "#f8fafc",
    borderRadius: 999,
    padding: "10px 16px",
    fontSize: 13,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    letterSpacing: ".02em",
  },
  badgeIcon: { fontSize: 16 },
  trustBand: {
    background: "#0f172a",
    color: "rgba(226, 232, 240, 0.85)",
    padding: "18px 0",
  },
  trustRow: {
    maxWidth: 1180,
    margin: "0 auto",
    padding: "0 26px",
    display: "flex",
    gap: 18,
    flexWrap: "wrap",
    justifyContent: "center",
    fontSize: 14,
    letterSpacing: ".08em",
    textTransform: "uppercase",
  },
  section: { padding: "72px 0" },
  sectionAlt: { padding: "72px 0", background: "#ffffff" },
  sectionDeep: {
    padding: "78px 0",
    background: "linear-gradient(135deg, #0b1f3a 0%, #112d52 52%, #132b4b 100%)",
    color: "#e2e8f0",
  },
  h2: {
    fontSize: 34,
    fontWeight: 900,
    margin: 0,
    color: "#0b1f3a",
    letterSpacing: "-0.01em",
  },
  h2Light: {
    fontSize: 34,
    fontWeight: 900,
    margin: 0,
    color: "#f8fafc",
    letterSpacing: "-0.01em",
  },
  leadSmall: { fontSize: 18, color: "#475569", marginTop: 12, lineHeight: 1.6 },
  leadLight: { fontSize: 18, color: "#cbd5f5", marginTop: 16, lineHeight: 1.6 },
  cards3: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 26,
    alignItems: "stretch",
  },
  cardService: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 20,
    padding: 28,
    boxShadow: "0 18px 36px rgba(15, 23, 42, 0.08)",
    display: "grid",
    gap: 12,
  },
  cardIcon: { fontSize: 36 },
  cardTitle: {
    fontWeight: 800,
    fontSize: 22,
    color: "#0b1f3a",
  },
  cardList: { margin: 0, paddingLeft: 18, lineHeight: 1.6, color: "#334155", fontSize: 15 },
  featureGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 26,
  },
  featureCard: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 20,
    padding: 26,
    boxShadow: "0 16px 34px rgba(15, 23, 42, 0.07)",
    display: "grid",
    gap: 10,
    textAlign: "left",
  },
  featureIcon: { fontSize: 30 },
  featureTitle: { fontSize: 20, fontWeight: 800, color: "#0b1f3a", margin: 0 },
  featureText: { margin: 0, fontSize: 15, color: "#334155", lineHeight: 1.7 },
  storyGrid: {
    maxWidth: 1180,
    margin: "0 auto",
    padding: "0 26px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 32,
    alignItems: "center",
  },
  storyPanel: {
    background: "rgba(7, 22, 43, 0.55)",
    borderRadius: 24,
    border: "1px solid rgba(148, 197, 255, 0.28)",
    padding: 28,
    display: "grid",
    gap: 14,
    boxShadow: "0 24px 60px rgba(4, 12, 24, 0.55)",
  },
  storyAccent: {
    fontSize: 15,
    letterSpacing: ".08em",
    textTransform: "uppercase",
    color: "#bae6fd",
    fontWeight: 700,
  },
  storyText: { fontSize: 17, lineHeight: 1.7, color: "#e2e8f0" },
  quote: {
    fontSize: 20,
    lineHeight: 1.6,
    color: "#f8fafc",
    fontWeight: 600,
  },
  quoteName: { fontSize: 15, color: "#cbd5f5" },
  processGrid: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 22,
  },
  processStep: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 20,
    padding: 26,
    display: "flex",
    alignItems: "flex-start",
    gap: 18,
    boxShadow: "0 18px 36px rgba(15, 23, 42, 0.07)",
  },
  stepNumber: {
    width: 44,
    height: 44,
    borderRadius: "999px",
    background: "#0b1f3a",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 16,
  },
  stepBody: { display: "grid", gap: 6 },
  stepTitle: { margin: 0, fontSize: 18, fontWeight: 700, color: "#0b1f3a" },
  stepText: { margin: 0, fontSize: 15, color: "#334155", lineHeight: 1.6 },
  faqList: { display: "grid", gap: 16 },
  faqItem: {
    border: "1px solid #e2e8f0",
    borderRadius: 18,
    background: "#ffffff",
    padding: 0,
    overflow: "hidden",
    boxShadow: "0 16px 32px rgba(15, 23, 42, 0.05)",
  },
  faqSummary: {
    padding: "18px 24px",
    listStyle: "none",
    cursor: "pointer",
    fontWeight: 700,
    color: "#0b1f3a",
    outline: "none",
    fontSize: 16,
  },
  faqContent: {
    margin: 0,
    padding: "0 24px 20px",
    fontSize: 15,
    color: "#334155",
    lineHeight: 1.7,
  },
  sectionContact: {
    padding: "78px 0",
    background: "linear-gradient(180deg, #f8fafc 0%, #e0f2fe 100%)",
  },
  contactSplit: {
    maxWidth: 1120,
    margin: "0 auto",
    padding: "0 26px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 32,
    alignItems: "stretch",
  },
  contactIntro: {
    display: "grid",
    gap: 18,
  },
  contactCard: {
    background: "#0f172a",
    color: "#e2e8f0",
    borderRadius: 24,
    padding: 32,
    boxShadow: "0 24px 50px rgba(15, 23, 42, 0.22)",
    border: "1px solid rgba(15, 23, 42, 0.5)",
    display: "grid",
    gap: 18,
  },
  contactList: {
    display: "grid",
    gap: 12,
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  contactListItem: {
    display: "grid",
    gap: 4,
  },
  contactLabel: {
    fontSize: 12,
    letterSpacing: ".08em",
    textTransform: "uppercase",
    color: "rgba(226, 232, 240, 0.7)",
  },
  contactValue: {
    fontSize: 18,
    fontWeight: 700,
    color: "#f8fafc",
  },
  contactCTA: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "14px 22px",
    borderRadius: 999,
    border: "1px solid rgba(148, 197, 255, 0.3)",
    background: "linear-gradient(135deg, rgba(59, 130, 246, 0.25), rgba(56, 189, 248, 0.45))",
    color: "#0f172a",
    fontWeight: 700,
    textDecoration: "none",
  },
  leadContact: { fontSize: 18, color: "#1e293b", lineHeight: 1.7 },
  contactGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 24,
    marginTop: 20,
  },
  contactTitle: {
    fontWeight: 800,
    color: "#0b1f3a",
    marginBottom: 10,
    fontSize: 18,
  },
  contactLine: { margin: "6px 0", fontSize: 15, color: "#334155" },
  contactLink: { color: "#0b1f3a", textDecoration: "none", fontWeight: 600 },
  privacyBox: {
    marginTop: 28,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 18,
    color: "#475569",
    boxShadow: "0 10px 24px rgba(148, 163, 184, 0.18)",
  },
  form: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 16,
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 20,
    padding: 24,
    marginTop: 18,
    boxShadow: "0 22px 46px rgba(15, 23, 42, 0.12)",
  },
  label: { display: "grid", gap: 8, fontSize: 14, color: "#0f172a", fontWeight: 600 },
  input: {
    padding: "12px 14px",
    borderRadius: 12,
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    outline: "none",
    fontSize: 15,
  },
  inputErr: { borderColor: "#ef4444", boxShadow: "0 0 0 3px rgba(239, 68, 68, 0.15)" },
  errText: { color: "#b91c1c", fontSize: 12 },
  ok: {
    background: "#ecfdf5",
    color: "#065f46",
    border: "1px solid #a7f3d0",
    padding: 14,
    borderRadius: 14,
    marginTop: 12,
    fontWeight: 600,
  },
  loading: {
    background: "#eff6ff",
    color: "#1d4ed8",
    border: "1px solid #bfdbfe",
    padding: 14,
    borderRadius: 14,
    marginTop: 12,
    textAlign: "center",
    fontWeight: 600,
  },
  tags: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 8 },
  tagItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    border: "1px solid #cbd5e1",
    borderRadius: 999,
    background: "#f8fafc",
    fontSize: 14,
    fontWeight: 500,
  },
  inlineRadios: { display: "flex", gap: 16, marginTop: 8, flexWrap: "wrap" },
  checkGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 12, marginTop: 10 },
  checkItem: { display: "flex", alignItems: "center", gap: 8 },
  footer: {
    borderTop: "1px solid rgba(148, 163, 184, 0.35)",
    padding: "40px 0 28px",
    background: "#0b162b",
    color: "#cbd5f5",
    marginTop: 60,
  },
  footerWrap: {
    maxWidth: 1180,
    margin: "0 auto",
    padding: "0 26px",
    display: "grid",
    gap: 28,
  },
  footerGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 26,
  },
  footerHeading: {
    fontSize: 14,
    textTransform: "uppercase",
    letterSpacing: ".12em",
    color: "rgba(226, 232, 240, 0.7)",
    fontWeight: 700,
  },
  footerText: { fontSize: 15, lineHeight: 1.7, color: "#e2e8f0" },
  footerList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "grid",
    gap: 8,
  },
  footerListItem: { fontSize: 15, color: "#e2e8f0" },
  footerLink: { color: "#38bdf8", textDecoration: "none" },
  footerLegal: {
    fontSize: 13,
    color: "rgba(226, 232, 240, 0.6)",
    textAlign: "center",
    borderTop: "1px solid rgba(148, 163, 184, 0.2)",
    paddingTop: 18,
  },
};
